availableSecrets:
  secretManager:
  - versionName: projects/${PROJECT_ID}/secrets/FRONTEND_URL/versions/latest
    env: 'FRONTEND_URL'
  # Assuming other secrets like CONTEXT_MANAGER_REDIS_HOST and CONTEXT_MANAGER_REDIS_PORT
  # are also managed in Secret Manager and need to be added here if not already present.
  # Example for Redis secrets:
  # - versionName: projects/${PROJECT_ID}/secrets/CONTEXT_MANAGER_REDIS_HOST/versions/latest
  #   env: 'REDIS_HOST'
  # - versionName: projects/${PROJECT_ID}/secrets/CONTEXT_MANAGER_REDIS_PORT/versions/latest
  #   env: 'REDIS_PORT'

steps:
- id: 'Build context-manager image'
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '${_GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_GAR_REPOSITORY}/context-manager-image:${SHORT_SHA}', '.']
  dir: 'main_service'

- id: 'Push context-manager image'
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', '${_GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_GAR_REPOSITORY}/context-manager-image:${SHORT_SHA}']

- id: 'Deploy context-manager to Cloud Run'
  name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'run'
    - 'deploy'
    - 'context-manager'
    - '--image'
    - '${_GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_GAR_REPOSITORY}/context-manager-image:${SHORT_SHA}'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--service-account'
    - '${_MAIN_SERVICE_SA}'
    - '--vpc-connector'
    - '${_VPC_CONNECTOR}'
    - '--vpc-egress'
    - 'all'
    - '--set-env-vars'
    - 'GOOGLE_CLOUD_PROJECT=${PROJECT_ID},CONTEXT_TTL_SECONDS=90'
    - '--min-instances=0'
    - '--max-instances=1'
  secretEnv:
    - 'FRONTEND_URL'
    # Add other secret environment variables here if needed, e.g.:
    # - 'REDIS_HOST'
    # - 'REDIS_PORT'

substitutions:
  _GAR_LOCATION: 'us-central1'
  _GAR_REPOSITORY: 'ccai-services'
  _MAIN_SERVICE_SA: 'context-manager-sa@${PROJECT_ID}.iam.gserviceaccount.com'
  _VPC_CONNECTOR: 'redis-connector'

options:
  logging: CLOUD_LOGGING_ONLY