steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '${_GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_GAR_REPOSITORY}/ccai-insights-function:${SHORT_SHA}', '.']
  dir: 'ccai_insights_function'

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '${_GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_GAR_REPOSITORY}/ccai-insights-function:${SHORT_SHA}']

- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'functions'
    - 'deploy'
    - 'ccai-insights-function'
    - '--gen2'
    - '--source=${_GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_GAR_REPOSITORY}/ccai-insights-function:${SHORT_SHA}'
    - '--trigger-bucket'
    - '${_TRIGGER_BUCKET}'
    - '--entry-point'
    - 'main'
    - '--runtime'
    - 'python312'
    - '--region'
    - 'us-central1'
    - '--service-account'
    - '${_SERVICE_ACCOUNT}'
    - '--set-env-vars'
    - 'GOOGLE_CLOUD_PROJECT=${PROJECT_ID},LOCATION=us-central1'
    - '--min-instances=0'
    - '--max-instances=1'

substitutions:
  _GAR_LOCATION: 'us-central1'
  _GAR_REPOSITORY: 'ccai-services'
  _TRIGGER_BUCKET: 'pg-transcript' # TODO: Replace with your actual bucket name
  _SERVICE_ACCOUNT: 'transcript-aggregator-sa@${PROJECT_ID}.iam.gserviceaccount.com' # TODO: Replace with your function's service account

options:
  logging: CLOUD_LOGGING_ONLY
